name: EN10168 Schema CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - '**/package-lock.json'
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - 'README.md'
      - '**/package-lock.json'
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install GraphicsMagick
        run: |
          sudo apt-get update 
          sudo apt-get install -y ghostscript graphicsmagick

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Set local paths
        run: npm run set-local-paths

      - name: Run validation and rendering tests
        run: npm run test

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      # commit updated path

      - name: Add, commit and push updated paths
        id: commit-paths
        if: steps.branch-name.outputs.is_default == 'false' || github.event_name != 'release'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update paths to local [skip ci]'
          file_pattern: 'partials-map.json'
          commit_options: '--no-verify'

  fossa:
    needs: setup-and-test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

    steps:
      - uses: actions/checkout@v3

      - name: FOSSA analysis
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}

      - name: FOSSA tests
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
